// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for ClassSemesters.
const (
	ClassSemestersFALL   ClassSemesters = "FALL"
	ClassSemestersSPRING ClassSemesters = "SPRING"
	ClassSemestersSUMMER ClassSemesters = "SUMMER"
	ClassSemestersWINTER ClassSemesters = "WINTER"
)

// Valid indicates whether the value is a known member of the ClassSemesters enum.
func (e ClassSemesters) Valid() bool {
	switch e {
	case ClassSemestersFALL:
		return true
	case ClassSemestersSPRING:
		return true
	case ClassSemestersSUMMER:
		return true
	case ClassSemestersWINTER:
		return true
	default:
		return false
	}
}

// Defines values for GradesSemester.
const (
	GradesSemesterFALL   GradesSemester = "FALL"
	GradesSemesterSPRING GradesSemester = "SPRING"
	GradesSemesterSUMMER GradesSemester = "SUMMER"
	GradesSemesterWINTER GradesSemester = "WINTER"
)

// Valid indicates whether the value is a known member of the GradesSemester enum.
func (e GradesSemester) Valid() bool {
	switch e {
	case GradesSemesterFALL:
		return true
	case GradesSemesterSPRING:
		return true
	case GradesSemesterSUMMER:
		return true
	case GradesSemesterWINTER:
		return true
	default:
		return false
	}
}

// Defines values for PeriodDayOfWeek.
const (
	FRIDAY    PeriodDayOfWeek = "FRIDAY"
	MONDAY    PeriodDayOfWeek = "MONDAY"
	SATURDAY  PeriodDayOfWeek = "SATURDAY"
	SUNDAY    PeriodDayOfWeek = "SUNDAY"
	THURSDAY  PeriodDayOfWeek = "THURSDAY"
	TUESDAY   PeriodDayOfWeek = "TUESDAY"
	WEDNESDAY PeriodDayOfWeek = "WEDNESDAY"
)

// Valid indicates whether the value is a known member of the PeriodDayOfWeek enum.
func (e PeriodDayOfWeek) Valid() bool {
	switch e {
	case FRIDAY:
		return true
	case MONDAY:
		return true
	case SATURDAY:
		return true
	case SUNDAY:
		return true
	case THURSDAY:
		return true
	case TUESDAY:
		return true
	case WEDNESDAY:
		return true
	default:
		return false
	}
}

// Defines values for PostClassesJSONBodySemester.
const (
	PostClassesJSONBodySemesterFALL   PostClassesJSONBodySemester = "FALL"
	PostClassesJSONBodySemesterSPRING PostClassesJSONBodySemester = "SPRING"
	PostClassesJSONBodySemesterSUMMER PostClassesJSONBodySemester = "SUMMER"
	PostClassesJSONBodySemesterWINTER PostClassesJSONBodySemester = "WINTER"
)

// Valid indicates whether the value is a known member of the PostClassesJSONBodySemester enum.
func (e PostClassesJSONBodySemester) Valid() bool {
	switch e {
	case PostClassesJSONBodySemesterFALL:
		return true
	case PostClassesJSONBodySemesterSPRING:
		return true
	case PostClassesJSONBodySemesterSUMMER:
		return true
	case PostClassesJSONBodySemesterWINTER:
		return true
	default:
		return false
	}
}

// Assignment defines model for Assignment.
type Assignment struct {
	Attachments   *[]Attachment  `json:"attachments,omitempty"`
	ClassSchedule *ClassSchedule `json:"class_schedule,omitempty"`

	// Description 課題の説明
	Description *string `json:"description,omitempty"`

	// Due 課題の提出期限 (ISO 8601形式)
	Due *time.Time `json:"due,omitempty"`

	// Id 課題ID
	Id *string `json:"id,omitempty"`

	// MaxScore 課題の最大得点
	MaxScore *int `json:"max_score,omitempty"`

	// Title 課題タイトル
	Title *string `json:"title,omitempty"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	// Name 添付ファイル名
	Name *string `json:"name,omitempty"`

	// Url 添付ファイルのURL
	Url *string `json:"url,omitempty"`
}

// Class defines model for Class.
type Class struct {
	// Credits 単位数
	Credits *int `json:"credits,omitempty"`

	// Department 学科
	Department *string `json:"department,omitempty"`

	// Id クラスID
	Id *string `json:"id,omitempty"`

	// Name クラス名
	Name *string `json:"name,omitempty"`

	// Periods 授業の時間割のリスト
	Periods *[]Period `json:"periods,omitempty"`

	// Semesters 開講学期のリスト
	Semesters *[]ClassSemesters `json:"semesters,omitempty"`

	// Teachers 担当教員のリスト
	Teachers *[]Teacher `json:"teachers,omitempty"`

	// Year 開講年度
	Year *int `json:"year,omitempty"`
}

// ClassSemesters defines model for Class.Semesters.
type ClassSemesters string

// ClassSchedule defines model for ClassSchedule.
type ClassSchedule struct {
	// ClassId クラスID
	ClassId *string `json:"class_id,omitempty"`

	// Count 授業回数
	Count *int `json:"count,omitempty"`

	// Description 授業の説明
	Description *string `json:"description,omitempty"`
}

// Grades defines model for Grades.
type Grades struct {
	Classes *[]struct {
		// ClassId クラスID
		ClassId *string `json:"class_id,omitempty"`

		// Score 成績
		Score *int `json:"score,omitempty"`
	} `json:"classes,omitempty"`

	// CreditsEarned 取得単位数
	CreditsEarned *int `json:"credits_earned,omitempty"`

	// Gpa GPA
	Gpa *float32 `json:"gpa,omitempty"`

	// Gpt GPT
	Gpt *float32 `json:"gpt,omitempty"`

	// Semester 学期
	Semester *GradesSemester `json:"semester,omitempty"`

	// StudentId 学生ID
	StudentId *string `json:"student_id,omitempty"`

	// Year 年度
	Year *int `json:"year,omitempty"`
}

// GradesSemester 学期
type GradesSemester string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Password パスワード
	Password string `json:"password"`

	// Username ユーザー名
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token 認証トークン
	Token *string `json:"token,omitempty"`
}

// Period defines model for Period.
type Period struct {
	// DayOfWeek 曜日
	DayOfWeek *PeriodDayOfWeek `json:"day_of_week,omitempty"`

	// EndTime 終了時刻 (HH:mm:ss)
	EndTime *string `json:"end_time,omitempty"`

	// Room 教室
	Room *string `json:"room,omitempty"`

	// StartTime 開始時刻 (HH:mm:ss)
	StartTime *string `json:"start_time,omitempty"`
}

// PeriodDayOfWeek 曜日
type PeriodDayOfWeek string

// Student defines model for Student.
type Student struct {
	// Department 学科
	Department *string `json:"department,omitempty"`

	// Grade 学年
	Grade *int `json:"grade,omitempty"`

	// Id 学生ID
	Id *string `json:"id,omitempty"`

	// Name 学生名
	Name *string `json:"name,omitempty"`
}

// StudnetAssignment defines model for StudnetAssignment.
type StudnetAssignment struct {
	// AssignmentId 課題ID
	AssignmentId *string       `json:"assignment_id,omitempty"`
	Attachments  *[]Attachment `json:"attachments,omitempty"`

	// Score 得点
	Score *int `json:"score,omitempty"`

	// StudentId 学生ID
	StudentId *string `json:"student_id,omitempty"`

	// SubmittedAt 提出日時 (ISO 8601形式)
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
}

// Teacher defines model for Teacher.
type Teacher struct {
	// Department 学科
	Department *string `json:"department,omitempty"`

	// Id 教員ID
	Id *string `json:"id,omitempty"`

	// Name 教員名
	Name *string `json:"name,omitempty"`
}

// PostClassesJSONBody defines parameters for PostClasses.
type PostClassesJSONBody struct {
	// Department 学科
	Department *string `json:"department,omitempty"`

	// Periods 授業の時間割のリスト
	Periods *[]Period `json:"periods,omitempty"`

	// Semester 学期
	Semester *PostClassesJSONBodySemester `json:"semester,omitempty"`

	// Year 年度
	Year *int `json:"year,omitempty"`
}

// PostClassesJSONBodySemester defines parameters for PostClasses.
type PostClassesJSONBodySemester string

// GetStudentsMeAssignmentsParams defines parameters for GetStudentsMeAssignments.
type GetStudentsMeAssignmentsParams struct {
	// ClassId クラスID
	ClassId string `form:"class_id" json:"class_id"`
}

// GetTeachersMeAssignmentsParams defines parameters for GetTeachersMeAssignments.
type GetTeachersMeAssignmentsParams struct {
	// ClassId クラスID
	ClassId string `form:"class_id" json:"class_id"`
}

// PostTeachersMeAssignmentsParams defines parameters for PostTeachersMeAssignments.
type PostTeachersMeAssignmentsParams struct {
	// ClassId クラスID
	ClassId string `form:"class_id" json:"class_id"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody = LoginRequest

// PostClassesJSONRequestBody defines body for PostClasses for application/json ContentType.
type PostClassesJSONRequestBody PostClassesJSONBody

// PostStudentsMeAssignmentsAssignmentIdJSONRequestBody defines body for PostStudentsMeAssignmentsAssignmentId for application/json ContentType.
type PostStudentsMeAssignmentsAssignmentIdJSONRequestBody = StudnetAssignment

// PostTeachersMeAssignmentsJSONRequestBody defines body for PostTeachersMeAssignments for application/json ContentType.
type PostTeachersMeAssignmentsJSONRequestBody = Assignment

// PatchTeachersMeAssignmentsAssignmentIdJSONRequestBody defines body for PatchTeachersMeAssignmentsAssignmentId for application/json ContentType.
type PatchTeachersMeAssignmentsAssignmentIdJSONRequestBody = Assignment

// PostTeachersMeAssignmentsAssignmentIdGradeJSONRequestBody defines body for PostTeachersMeAssignmentsAssignmentIdGrade for application/json ContentType.
type PostTeachersMeAssignmentsAssignmentIdGradeJSONRequestBody = StudnetAssignment

// PostTeachersMeClassesJSONRequestBody defines body for PostTeachersMeClasses for application/json ContentType.
type PostTeachersMeClassesJSONRequestBody = Class

// PatchTeachersMeClassesClassIdJSONRequestBody defines body for PatchTeachersMeClassesClassId for application/json ContentType.
type PatchTeachersMeClassesClassIdJSONRequestBody = Class
