// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostAuthLogin ログイン
	// (POST /auth/login)
	PostAuthLogin(ctx echo.Context) error
	// PostAuthLogout ログアウト
	// (POST /auth/logout)
	PostAuthLogout(ctx echo.Context) error
	// PostAuthSignup サインアップ
	// (POST /auth/signup)
	PostAuthSignup(ctx echo.Context) error
	// PostClasses 講義情報検索
	// (POST /classes)
	PostClasses(ctx echo.Context) error
	// GetStudentsMe 自分の情報を取得
	// (GET /students/me)
	GetStudentsMe(ctx echo.Context) error
	// GetStudentsMeAssignments 自分の課題情報を取得
	// (GET /students/me/assignments)
	GetStudentsMeAssignments(ctx echo.Context, params GetStudentsMeAssignmentsParams) error
	// GetStudentsMeAssignmentsAssignmentId 自分の課題提出情報を取得
	// (GET /students/me/assignments/{assignment_id})
	GetStudentsMeAssignmentsAssignmentId(ctx echo.Context, assignmentId string) error
	// PostStudentsMeAssignmentsAssignmentId 自分の課題を提出
	// (POST /students/me/assignments/{assignment_id})
	PostStudentsMeAssignmentsAssignmentId(ctx echo.Context, assignmentId string) error
	// GetStudentsMeClasses 自分の履修情報を取得
	// (GET /students/me/classes)
	GetStudentsMeClasses(ctx echo.Context) error
	// GetStudentsMeClassesClassId 自分の指定したクラスの情報を取得
	// (GET /students/me/classes/{class_id})
	GetStudentsMeClassesClassId(ctx echo.Context, classId string) error
	// GetStudentsMeGrades 自分の成績情報を取得
	// (GET /students/me/grades)
	GetStudentsMeGrades(ctx echo.Context) error
	// GetTeachersMe 自分の情報を取得
	// (GET /teachers/me)
	GetTeachersMe(ctx echo.Context) error
	// GetTeachersMeAssignments 自分の担当クラスの課題情報を取得
	// (GET /teachers/me/assignments)
	GetTeachersMeAssignments(ctx echo.Context, params GetTeachersMeAssignmentsParams) error
	// PostTeachersMeAssignments 自分の担当クラスの課題を追加
	// (POST /teachers/me/assignments)
	PostTeachersMeAssignments(ctx echo.Context, params PostTeachersMeAssignmentsParams) error
	// DeleteTeachersMeAssignmentsAssignmentId 自分の担当クラスの課題情報を削除
	// (DELETE /teachers/me/assignments/{assignment_id})
	DeleteTeachersMeAssignmentsAssignmentId(ctx echo.Context, assignmentId string) error
	// GetTeachersMeAssignmentsAssignmentId 自分の担当クラスの課題情報を取得
	// (GET /teachers/me/assignments/{assignment_id})
	GetTeachersMeAssignmentsAssignmentId(ctx echo.Context, assignmentId string) error
	// PatchTeachersMeAssignmentsAssignmentId 自分の担当クラスの課題情報を更新
	// (PATCH /teachers/me/assignments/{assignment_id})
	PatchTeachersMeAssignmentsAssignmentId(ctx echo.Context, assignmentId string) error
	// PostTeachersMeAssignmentsAssignmentIdGrade 自分の担当クラスの課題提出情報に採点
	// (POST /teachers/me/assignments/{assignment_id}/grade)
	PostTeachersMeAssignmentsAssignmentIdGrade(ctx echo.Context, assignmentId string) error
	// GetTeachersMeAssignmentsAssignmentIdSubmissions 自分の担当クラスの課題提出情報を取得
	// (GET /teachers/me/assignments/{assignment_id}/submissions)
	GetTeachersMeAssignmentsAssignmentIdSubmissions(ctx echo.Context, assignmentId string) error
	// GetTeachersMeClasses 自分の担当クラス情報を取得
	// (GET /teachers/me/classes)
	GetTeachersMeClasses(ctx echo.Context) error
	// PostTeachersMeClasses 自分の担当クラスを追加
	// (POST /teachers/me/classes)
	PostTeachersMeClasses(ctx echo.Context) error
	// GetTeachersMeClassesClassId 自分の担当クラスの情報を取得
	// (GET /teachers/me/classes/{class_id})
	GetTeachersMeClassesClassId(ctx echo.Context, classId string) error
	// PatchTeachersMeClassesClassId 自分の担当クラスの情報を更新
	// (PATCH /teachers/me/classes/{class_id})
	PatchTeachersMeClassesClassId(ctx echo.Context, classId string) error
	// GetTeachersMeClassesClassIdStudents 自分の担当クラスの学生情報を取得
	// (GET /teachers/me/classes/{class_id}/students)
	GetTeachersMeClassesClassIdStudents(ctx echo.Context, classId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostAuthLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogin(ctx)
	return err
}

// PostAuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthLogout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthLogout(ctx)
	return err
}

// PostAuthSignup converts echo context to params.
func (w *ServerInterfaceWrapper) PostAuthSignup(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAuthSignup(ctx)
	return err
}

// PostClasses converts echo context to params.
func (w *ServerInterfaceWrapper) PostClasses(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostClasses(ctx)
	return err
}

// GetStudentsMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMe(ctx)
	return err
}

// GetStudentsMeAssignments converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMeAssignments(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStudentsMeAssignmentsParams
	// ------------- Required query parameter "class_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "class_id", ctx.QueryParams(), &params.ClassId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMeAssignments(ctx, params)
	return err
}

// GetStudentsMeAssignmentsAssignmentId converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMeAssignmentsAssignmentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMeAssignmentsAssignmentId(ctx, assignmentId)
	return err
}

// PostStudentsMeAssignmentsAssignmentId converts echo context to params.
func (w *ServerInterfaceWrapper) PostStudentsMeAssignmentsAssignmentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStudentsMeAssignmentsAssignmentId(ctx, assignmentId)
	return err
}

// GetStudentsMeClasses converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMeClasses(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMeClasses(ctx)
	return err
}

// GetStudentsMeClassesClassId converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMeClassesClassId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "class_id" -------------
	var classId string

	err = runtime.BindStyledParameterWithOptions("simple", "class_id", ctx.Param("class_id"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMeClassesClassId(ctx, classId)
	return err
}

// GetStudentsMeGrades converts echo context to params.
func (w *ServerInterfaceWrapper) GetStudentsMeGrades(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStudentsMeGrades(ctx)
	return err
}

// GetTeachersMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMe(ctx)
	return err
}

// GetTeachersMeAssignments converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeAssignments(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeachersMeAssignmentsParams
	// ------------- Required query parameter "class_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "class_id", ctx.QueryParams(), &params.ClassId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeAssignments(ctx, params)
	return err
}

// PostTeachersMeAssignments converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeachersMeAssignments(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTeachersMeAssignmentsParams
	// ------------- Required query parameter "class_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "class_id", ctx.QueryParams(), &params.ClassId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeachersMeAssignments(ctx, params)
	return err
}

// DeleteTeachersMeAssignmentsAssignmentId converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTeachersMeAssignmentsAssignmentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTeachersMeAssignmentsAssignmentId(ctx, assignmentId)
	return err
}

// GetTeachersMeAssignmentsAssignmentId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeAssignmentsAssignmentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeAssignmentsAssignmentId(ctx, assignmentId)
	return err
}

// PatchTeachersMeAssignmentsAssignmentId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTeachersMeAssignmentsAssignmentId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTeachersMeAssignmentsAssignmentId(ctx, assignmentId)
	return err
}

// PostTeachersMeAssignmentsAssignmentIdGrade converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeachersMeAssignmentsAssignmentIdGrade(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeachersMeAssignmentsAssignmentIdGrade(ctx, assignmentId)
	return err
}

// GetTeachersMeAssignmentsAssignmentIdSubmissions converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeAssignmentsAssignmentIdSubmissions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "assignment_id" -------------
	var assignmentId string

	err = runtime.BindStyledParameterWithOptions("simple", "assignment_id", ctx.Param("assignment_id"), &assignmentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter assignment_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeAssignmentsAssignmentIdSubmissions(ctx, assignmentId)
	return err
}

// GetTeachersMeClasses converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeClasses(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeClasses(ctx)
	return err
}

// PostTeachersMeClasses converts echo context to params.
func (w *ServerInterfaceWrapper) PostTeachersMeClasses(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTeachersMeClasses(ctx)
	return err
}

// GetTeachersMeClassesClassId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeClassesClassId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "class_id" -------------
	var classId string

	err = runtime.BindStyledParameterWithOptions("simple", "class_id", ctx.Param("class_id"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeClassesClassId(ctx, classId)
	return err
}

// PatchTeachersMeClassesClassId converts echo context to params.
func (w *ServerInterfaceWrapper) PatchTeachersMeClassesClassId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "class_id" -------------
	var classId string

	err = runtime.BindStyledParameterWithOptions("simple", "class_id", ctx.Param("class_id"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchTeachersMeClassesClassId(ctx, classId)
	return err
}

// GetTeachersMeClassesClassIdStudents converts echo context to params.
func (w *ServerInterfaceWrapper) GetTeachersMeClassesClassIdStudents(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "class_id" -------------
	var classId string

	err = runtime.BindStyledParameterWithOptions("simple", "class_id", ctx.Param("class_id"), &classId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter class_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTeachersMeClassesClassIdStudents(ctx, classId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.PostAuthLogin, options.OperationMiddlewares["PostAuthLogin"]...)
	router.POST(options.BaseURL+"/auth/signup", wrapper.PostAuthSignup, options.OperationMiddlewares["PostAuthSignup"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout, options.OperationMiddlewares["PostAuthLogout"]...)
	router.GET(options.BaseURL+"/students/me", wrapper.GetStudentsMe, options.OperationMiddlewares["GetStudentsMe"]...)
	router.GET(options.BaseURL+"/students/me/classes", wrapper.GetStudentsMeClasses, options.OperationMiddlewares["GetStudentsMeClasses"]...)
	router.GET(options.BaseURL+"/students/me/classes/:class_id", wrapper.GetStudentsMeClassesClassId, options.OperationMiddlewares["GetStudentsMeClassesClassId"]...)
	router.GET(options.BaseURL+"/students/me/assignments", wrapper.GetStudentsMeAssignments, options.OperationMiddlewares["GetStudentsMeAssignments"]...)
	router.GET(options.BaseURL+"/students/me/assignments/:assignment_id", wrapper.GetStudentsMeAssignmentsAssignmentId, options.OperationMiddlewares["GetStudentsMeAssignmentsAssignmentId"]...)
	router.POST(options.BaseURL+"/students/me/assignments/:assignment_id", wrapper.PostStudentsMeAssignmentsAssignmentId, options.OperationMiddlewares["PostStudentsMeAssignmentsAssignmentId"]...)
	router.GET(options.BaseURL+"/students/me/grades", wrapper.GetStudentsMeGrades, options.OperationMiddlewares["GetStudentsMeGrades"]...)
	router.GET(options.BaseURL+"/teachers/me", wrapper.GetTeachersMe, options.OperationMiddlewares["GetTeachersMe"]...)
	router.GET(options.BaseURL+"/teachers/me/classes", wrapper.GetTeachersMeClasses, options.OperationMiddlewares["GetTeachersMeClasses"]...)
	router.POST(options.BaseURL+"/teachers/me/classes", wrapper.PostTeachersMeClasses, options.OperationMiddlewares["PostTeachersMeClasses"]...)
	router.GET(options.BaseURL+"/teachers/me/classes/:class_id", wrapper.GetTeachersMeClassesClassId, options.OperationMiddlewares["GetTeachersMeClassesClassId"]...)
	router.PATCH(options.BaseURL+"/teachers/me/classes/:class_id", wrapper.PatchTeachersMeClassesClassId, options.OperationMiddlewares["PatchTeachersMeClassesClassId"]...)
	router.GET(options.BaseURL+"/teachers/me/assignments", wrapper.GetTeachersMeAssignments, options.OperationMiddlewares["GetTeachersMeAssignments"]...)
	router.POST(options.BaseURL+"/teachers/me/assignments", wrapper.PostTeachersMeAssignments, options.OperationMiddlewares["PostTeachersMeAssignments"]...)
	router.DELETE(options.BaseURL+"/teachers/me/assignments/:assignment_id", wrapper.DeleteTeachersMeAssignmentsAssignmentId, options.OperationMiddlewares["DeleteTeachersMeAssignmentsAssignmentId"]...)
	router.GET(options.BaseURL+"/teachers/me/assignments/:assignment_id", wrapper.GetTeachersMeAssignmentsAssignmentId, options.OperationMiddlewares["GetTeachersMeAssignmentsAssignmentId"]...)
	router.PATCH(options.BaseURL+"/teachers/me/assignments/:assignment_id", wrapper.PatchTeachersMeAssignmentsAssignmentId, options.OperationMiddlewares["PatchTeachersMeAssignmentsAssignmentId"]...)
	router.GET(options.BaseURL+"/teachers/me/classes/:class_id/students", wrapper.GetTeachersMeClassesClassIdStudents, options.OperationMiddlewares["GetTeachersMeClassesClassIdStudents"]...)
	router.GET(options.BaseURL+"/teachers/me/assignments/:assignment_id/submissions", wrapper.GetTeachersMeAssignmentsAssignmentIdSubmissions, options.OperationMiddlewares["GetTeachersMeAssignmentsAssignmentIdSubmissions"]...)
	router.POST(options.BaseURL+"/teachers/me/assignments/:assignment_id/grade", wrapper.PostTeachersMeAssignmentsAssignmentIdGrade, options.OperationMiddlewares["PostTeachersMeAssignmentsAssignmentIdGrade"]...)
	router.POST(options.BaseURL+"/classes", wrapper.PostClasses, options.OperationMiddlewares["PostClasses"]...)

}
