// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fv/b9vGFf9XjNt+6AAtctZiGPSb6nwzljiGZaMYAsNgxLPM1iSVu+M6LxBQU0jj1PniNIsd1cbcBI6z",
	"5oubpOlWJ3byx9CkpP9iuCNFUeJRIinKVoL8FDriu7v33uc+7/PupMsgr8pFVYEKwSBzGeD8HJQF9pjF",
	"WCooMlQI/auI1CJERILsM4EQIT8nN6wkAmX28HsEZ0EG/C7dHDXtDJnOujaglAJkoQhBBggICQv07/y8",
	"gPEMfVfU5mG3sUbo27nGy6UUECHOI6lIJFWhti1/gtrjl/X7143Fndrjp9a9m8CdHRMkKQVmr8EOdtat",
	"FfPqa2tjs15ZGfpkNHd+6C9/Hj5u7j8w9279AaTArIpkgYAMEAUC/0gkGfLmkMSgKUZP8N6XhX/M4LyK",
	"Oq5s4xtz65H5dq2q7zbHkBQCCxCxOEtkPngA/Z2hbxnlJaP8xL+CZpbUi1/CPEubJ4k+UCiCzJnJ+t+b",
	"gzf3jPJdQ7/PJntirtzguauh+TDWxuLO1MTZcKtlMPEvNI+gKNnIbZ3NvHHvYP+Gdfc5N5QiLAqINHxv",
	"s3y2XX10O2zWDf1no/yToe/yE88PpGsUEL8iRJIqcryybi5ZD59RsFT0+uod89pLY3HHKD829F2jvARS",
	"4bbvOBuet3UxlCEmEHGmrq8u156um8+2rY3NoEmhoskgcwHkxidGx06DFMhNnTt3cgKkwKnsWZroL0bH",
	"Jk9OgGmOz+1LIVDIz3FXYi1fMffvWHcr5p37cdyftEfmTboABRTo+u4r8/U2B06BcM15KLANtowiY+Ap",
	"r2o8zNq4MNf/HQz4DqTqoiqIVHkenkaCCHGAa7C1liTkfACDWksr1d/ehkyMr1jZBDIDBaRAzpLMW6vm",
	"27XObFIoCn7D0+NZbzmZnVcF0rRWNPliw5jwjCdDGTf2K5fFrI1NkOppT2KiiVAh3FxRmvzXJj9R/G0U",
	"aQOdVQuSMgEvaRBz6lNRwPhrFfEgVL7N2OBno7xnlK9xqxOGKICXy9vUTP+vUd7jUnMpBRC8pEmIQuVC",
	"c6RUc0XTwc7goqpgDhsQ9SvI1To3av/ZYyV9j+2MX8LtTIfefdOIwsKMOjvzNYRfcTbR+oa19tCDl3Pn",
	"x05k/wZSYHLqZM5++uLkibHG8+SZqQnn8dTEqP2Qy05OTTiPU8yaByqoiDNMV/nWUP1VP3j9rVXRzaU3",
	"Q5+cOZOR5QzGLaosSJAhVZU5Tt2tmDtbXCohAiIBy6ivLpuPlmMsg5eMnL2FONmIJUEKlHW5BubuKy45",
	"Rd27/J1hWwTtCa7XCiQd+w73s5moajr5liWgsnQQ43GpEWsXZYkQKM4IvDpudydrD62KHrc74eWjIXkS",
	"QiHPaVuPRcGUbRESU/S/JGVW9Q8zpUh/hwhLZGEoOz4K3D7J/wH7i9kcPzZ8bJiuTC1CRShKIAM+PTZ8",
	"7FNG5GSOhSYtaGQuPU+pm8VNxYRXMZ4Z+nPWzvxiLFYMfRmwQZFAXxgVQQaMq5hkNTLHigCwCwjE5HNV",
	"XGBqSFWIE36hWJyX8swy/SW2lZqN327obqmWpdYyRZAG2X/Y5Yf59qfh4aTndoobm7w1Ruf/SiP92fBx",
	"Xu5okFUk/ROKLOtYk2UBLbRFliZVKGBalmgkwTR91c2PqpHuCXpg6Nu0lHbNER3NF63P/AOPqUMjTvh6",
	"8M5ZVgcHKUtqxWAHrdXnte1bXuVSrbypX3/ZxdOcPeygwPH44cFxBEGBQNHO2rA/oJ8L4lBz7S1J0391",
	"drr+wCiXjfIaP2+eFoifs9rT9erbn6zyFfPHF4b+vbW1UX31oEPCRpwB42crCdY/8lOJPnU5PXcryfNt",
	"qIDZR2K+eAUTMJfFyNApVVPa+cmLUBueHqiPqLKsKg7YHSGE03aJL8AuVfLgN4oUWyJRyDQ2gd1oB2yC",
	"05A4Qhqfg6CPxawh1xMrY7Wrj82lb/2OesLZ8Mwf0HRTJONYwb1+1dz5wVhcMxY33bMVds5DxXWM0Gc9",
	"66FSCQkytI8LL3Q+y6EaClzSIFoADTnYPAdq3z0pT7LaheH0YewsT98SYXvFBAY3GZHhkb7c0lCVeoVL",
	"+4VJT1hpPo6K3XDjafwYaKgeb2KmtWs8TOB0Y43WdrdvMOFlgw+WVIiWJQYADvY3rKWVDmJlsBGQvNgN",
	"SP7hKd5Q6GtRvT1BkApWBolwHOURw1H5yHzx8OBdHIXg1csDp8JiBp8bjEgpSF9uVNxSkmIifn7YP935",
	"gKMkWinhSIRECEwkryHDpSAcKgruBV5kJLALtxh5d+4M+xh5Z4Y+hJ7nc3CgG7fX0boi9047dGydg90+",
	"d0XujfkhdkUNz/wBjdkVNYPLvj/QQz/UDPrHfqgPkAiXHj5UwovernAw9O9r7/bN737soHUHDgnJy9uj",
	"07X9F7RdUx+Zj3htuAjnIYEJU9S17+qVrQBknmATcrE5mJ144tcrEciEBTKITAajtHzoxyd9PTfptZwI",
	"JD+XLAas9VfW6vOgqkLnG2wUHH2N+VCgZyOh5yKTdr8VlJj4aTn0W3xi3bxfpZ9GE0JexLLG7OPJ3/t3",
	"7hwJIb1DmX0/CmNJVZLt7aLdYnSFc86zzPe0Iofq/DgIO7oGsMvdRwfERT+EDkJUDAh9iKfRnaPSt948",
	"Ukve+7dmQp7xHl5LHHiw3I9uOFoT3NMlQwf+jr/hPl4v9Ey8h9gkxWqPBibTR8ov7zWyovRAfo5xb7SS",
	"IRv7iqtnynEvg95L6gktDI9KDnKzFICgkvvf/J9XNWPNvsBbSgX98uW2sXjb/hmB876bZL9N45cNPht3",
	"ZZx5rryof/NDy9vO9yxL06X/BwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
